package dataStructures.hashTables;

/**
 * HastTable
 */
public class HashTable {
    // Hash Table is used to add key value pair to an address.
    // It is both "one way" (can get address using key but cannot get key using address) and "deterministic" (always get same address)

    // Collision - A collision occurs when more than one value to be hashed by a particular hash function 
    // hash to the same slot in the table or data structure (hash table) being generated by the hash function.

    // Collision can be handled by -
    // 1. Adding the key value pair to same address, also known as "Separate Chaining". eg. Linked List
    // 2. Adding the key value pair to the next open address (non consumed one), also known as "Linear Probing" or "Open Addressing" 

    private int size = 7;
    private Node[] dataMap;

    class Node {
        String key;
        int value;
        Node next;

        Node (String key, int value) {
            this.key = key;
            this.value = value;
        }
    }

    public HashTable () {
        dataMap = new Node[size];
    }

    public void printTable() {
        for (int i=0; i<size; i++) {
            System.out.print(i + " : ");
            Node tempNode = dataMap[i];
            while (tempNode != null) {
                System.out.println(" { " + tempNode.key + " = " + tempNode.value + " } ");
                tempNode = tempNode.next;
            }
        }
    }
}